### ISSUE TITLE
fence_virtd can't be killed cleanly

### ISSUE THREAD

**Issue by andyprice** [ClusterLabs/fence-virt#10]
Since commit 2c909b78d8226d4d76f53df1091af40ec5fc54a1, control doesn't return to the dispatch loop in `main()` after `select()` returns with EINTR:

    while (run && lp->dispatch(listener_ctx, NULL) >= 0);

The signal handler zeroes `run` when SIGINT, SIGTERM or SIGQUIT is caught but now it never gets checked after the first time because the loop now continues inside `->dispatch` on EINTR.

This is causing fence_virtd.service to take 1.5 minutes to stop after SIGTERM is sent as that is the time limit before it gets sent a SIGKILL.

Tested with the multicast listener.

**Comment by andyprice** [comment]
Thanks!

**Comment by ryan-mccabe** [comment]
Thanks for the catch. Glad at least somebody is running off master.

**Comment by andyprice** [comment]
I found the bug in rawhide but I did check master before I filed the issue.
