### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by Thermi** [ClusterLabs/fence-virt#11]
Hello,

Where do I find releases of fence-virt? If there are none, please adopt the convention of using Github releases, because doing that is very easy.

Kind regards

Thermi

**Comment by jnpkrn** [comment]
I don't scan it regularly here, nor I am a maintainer, but you can find
the releases here:

  https://people.redhat.com/rmccabe/fence-virt/

(can be derived, e.g., from here, but I agree this visibility is pretty low:
https://src.fedoraproject.org/rpms/fence-virt/blob/master/f/fence-virt.spec)

Hope this helps.

**Comment by oalbrigt** [comment]
We've now tagged the releases from https://people.redhat.com/rmccabe/fence-virt/, so you can also get them under Releases on github.
