### ISSUE TITLE
pm-fence plugin not in sync with pacemaker codebase at least since Pacemaker-1.1.8

### ISSUE THREAD

**Issue by jnpkrn** [ClusterLabs/fence-virt#12]
See https://lists.clusterlabs.org/pipermail/developers/2018-November/001320.html

The question is whether any non-linear topology (nesting?) makes
(or ever made) sense for some (niche?) use cases, and if so, the
task is to get `server/pm-fence.c` back in sync with pacemaker's
(unstable) API.

**Comment by oalbrigt** [comment]
According to Ryan there hasnt been any development of this while he's been the maintainer for the project.
