### ISSUE TITLE
I must reload the fence_virtd on my host to connect to host again

### ISSUE THREAD

**Issue by idonotknow** [ClusterLabs/fence-virt#9]
Just as I describe above,I have tried fence kvm vms on two hosts,and I can access to each other then.But after a few minutes or so,I will lose connection to host and must reload the fence_virtd daemon to make it success again. I wonder if there is one way to make the connection persistent?
Thank you in advance for help.

**Comment by ryan-mccabe** [comment]
This should be resolved by https://github.com/ClusterLabs/fence-virt/commit/5e04644e319e8b1ab3909da0fd5abf0460bad3c8
